# Generated by Django 2.2.4 on 2019-09-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('state', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Done')], default=0)),
                ('children', models.ManyToManyField(related_name='_task_children_+', to='todo.Task')),
            ],
        ),
    ]
