# Generated by Django 2.2.4 on 2019-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_children_+', to='todo.Task'),
        ),
    ]
