# Generated by Django 2.2.4 on 2019-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190901_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_task_children_+', to='todo.Task'),
        ),
    ]
